apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-transfer-service-config
data:
  SPRING_PROFILES_ACTIVE: kubernetes
  SPRING_APPLICATION_NAME: transfer-service
  SERVER_PORT: "8084"
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: "http://{{ .Release.Name }}-keycloak:{{ .Values.global.keycloak.port }}/realms/{{ .Values.global.keycloak.realm }}"
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_ACCOUNTS_CLIENT_ID: transfer-service
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_ACCOUNTS_AUTHORIZATION_GRANT_TYPE: client_credentials
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_ACCOUNTS_SCOPE: accounts
  SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_ACCOUNTS_ISSUER_URI: "http://{{ .Release.Name }}-keycloak:{{ .Values.global.keycloak.port }}/realms/{{ .Values.global.keycloak.realm }}"
  ACCOUNTS_SERVICE_URL: "http://{{ .Release.Name }}-accounts-service:8081"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "{{ .Release.Name }}-kafka:9092"
  SPRING_KAFKA_PRODUCER_KEY_SERIALIZER: org.apache.kafka.common.serialization.StringSerializer
  SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER: org.springframework.kafka.support.serializer.JsonSerializer
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: health,prometheus,info
  MANAGEMENT_METRICS_DISTRIBUTION_PERCENTILES__HISTOGRAM_HTTP_SERVER_REQUESTS: "true"
  MANAGEMENT_TRACING_SAMPLING_PROBABILITY: "1.0"
  MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: "http://{{ .Release.Name }}-zipkin:9411/api/v2/spans"
  LOGSTASH_HOST: "{{ .Release.Name }}-logstash"
  LOGSTASH_PORT: "5044"
