apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-transfer-service
  labels:
    app: transfer-service
spec:
  type: ClusterIP
  ports:
    - port: 8084
      targetPort: 8084
  selector:
    app: transfer-service
