# Accounts Service settings
server.port=8081

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/accounts_db
spring.datasource.username=accounts
spring.datasource.password=${ACCOUNTS_DB_PASSWORD}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.sql.init.mode=always

# OAuth2 Resource Server - validate incoming JWT
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/realms/my-bank

# Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
