# Gateway settings
server.port=8090

# JWT validation
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/realms/my-bank

# Enable service discovery for routes
spring.cloud.gateway.discovery.locator.enabled=false

# Routes to microservices via Eureka (lb = load balanced)
spring.cloud.gateway.routes[0].id=accounts-service
spring.cloud.gateway.routes[0].uri=lb://accounts-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/accounts/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1

spring.cloud.gateway.routes[1].id=cash-service
spring.cloud.gateway.routes[1].uri=lb://cash-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/cash/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1

spring.cloud.gateway.routes[2].id=notifications-service
spring.cloud.gateway.routes[2].uri=lb://notifications-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/notifications/**
spring.cloud.gateway.routes[2].filters[0]=StripPrefix=1

spring.cloud.gateway.routes[3].id=transfer-service
spring.cloud.gateway.routes[3].uri=lb://transfer-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/transfer/**
spring.cloud.gateway.routes[3].filters[0]=StripPrefix=1
