# Notifications Service settings
server.port=8083

# OAuth2 Resource Server - validate incoming JWT with scope 'notifications'
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/realms/my-bank
