apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-notifications-service-config
data:
  SPRING_PROFILES_ACTIVE: kubernetes
  SPRING_APPLICATION_NAME: notifications-service
  SERVER_PORT: "8083"
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: "http://{{ .Release.Name }}-keycloak:{{ .Values.global.keycloak.port }}/realms/{{ .Values.global.keycloak.realm }}"
