apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-notifications-service-config
data:
  SPRING_PROFILES_ACTIVE: kubernetes
  SPRING_APPLICATION_NAME: notifications-service
  SERVER_PORT: "8083"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "{{ .Release.Name }}-kafka:9092"
  SPRING_KAFKA_CONSUMER_GROUP_ID: notifications-group
  SPRING_KAFKA_CONSUMER_AUTO_OFFSET_RESET: earliest
  SPRING_KAFKA_CONSUMER_KEY_DESERIALIZER: org.apache.kafka.common.serialization.StringDeserializer
  SPRING_KAFKA_CONSUMER_VALUE_DESERIALIZER: org.springframework.kafka.support.serializer.JsonDeserializer
  SPRING_KAFKA_CONSUMER_PROPERTIES_SPRING_JSON_TRUSTED_PACKAGES: "*"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: health,prometheus,info
  MANAGEMENT_TRACING_SAMPLING_PROBABILITY: "1.0"
  MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: "http://{{ .Release.Name }}-zipkin:9411/api/v2/spans"
  LOGSTASH_HOST: "{{ .Release.Name }}-logstash"
  LOGSTASH_PORT: "5044"
