apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-notifications-service
  labels:
    app: notifications-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: notifications-service
  template:
    metadata:
      labels:
        app: notifications-service
    spec:
      containers:
        - name: notifications-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8083
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-notifications-service-config
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 60
            periodSeconds: 30
