apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-notifications-service
  labels:
    app: notifications-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: notifications-service
  template:
    metadata:
      labels:
        app: notifications-service
    spec:
      containers:
        - name: notifications-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-notifications-service-config
          readinessProbe:
            exec:
              command: ["sh", "-c", "ps aux | grep java | grep -v grep"]
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            exec:
              command: ["sh", "-c", "ps aux | grep java | grep -v grep"]
            initialDelaySeconds: 60
            periodSeconds: 30
