apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-accounts-service-config
data:
  SPRING_PROFILES_ACTIVE: kubernetes
  SPRING_APPLICATION_NAME: accounts-service
  SERVER_PORT: "8081"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://{{ .Release.Name }}-accounts-db:{{ .Values.db.port }}/{{ .Values.db.name }}"
  SPRING_DATASOURCE_USERNAME: {{ .Values.db.username | quote }}
  SPRING_JPA_HIBERNATE_DDL_AUTO: update
  SPRING_JPA_OPEN_IN_VIEW: "false"
  SPRING_SQL_INIT_MODE: always
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: "http://{{ .Release.Name }}-keycloak:{{ .Values.global.keycloak.port }}/realms/{{ .Values.global.keycloak.realm }}"
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_NOTIFICATIONS_CLIENT_ID: accounts-service
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_NOTIFICATIONS_AUTHORIZATION_GRANT_TYPE: client_credentials
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_NOTIFICATIONS_SCOPE: notifications
  SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_NOTIFICATIONS_ISSUER_URI: "http://{{ .Release.Name }}-keycloak:{{ .Values.global.keycloak.port }}/realms/{{ .Values.global.keycloak.realm }}"
  NOTIFICATIONS_SERVICE_URL: "http://{{ .Release.Name }}-notifications-service:8083"
