apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-accounts-service
  labels:
    app: accounts-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: accounts-service
  template:
    metadata:
      labels:
        app: accounts-service
    spec:
      containers:
        - name: accounts-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-accounts-service-config
            - secretRef:
                name: {{ .Release.Name }}-accounts-service-secret
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 30
