apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-accounts-service-secret
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: {{ .Values.global.secrets.accountsDbPassword | quote }}
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_NOTIFICATIONS_CLIENT_SECRET: {{ .Values.global.secrets.accountsClientSecret | quote }}
