apiVersion: v2
name: my-bank
description: My Bank - Microservices application deployed on Kubernetes
type: application
version: 0.1.0
appVersion: "0.0.1"

dependencies:
  - name: accounts-db
    version: "0.1.0"
    repository: "file://charts/accounts-db"
  - name: kafka
    version: "0.1.0"
    repository: "file://charts/kafka"
  - name: keycloak
    version: "0.1.0"
    repository: "file://charts/keycloak"
  - name: accounts-service
    version: "0.1.0"
    repository: "file://charts/accounts-service"
  - name: cash-service
    version: "0.1.0"
    repository: "file://charts/cash-service"
  - name: transfer-service
    version: "0.1.0"
    repository: "file://charts/transfer-service"
  - name: notifications-service
    version: "0.1.0"
    repository: "file://charts/notifications-service"
  - name: front-app
    version: "0.1.0"
    repository: "file://charts/front-app"
  - name: zipkin
    version: "0.1.0"
    repository: "file://charts/zipkin"
  - name: prometheus
    version: "0.1.0"
    repository: "file://charts/prometheus"
  - name: grafana
    version: "0.1.0"
    repository: "file://charts/grafana"
  - name: elasticsearch
    version: "0.1.0"
    repository: "file://charts/elasticsearch"
  - name: logstash
    version: "0.1.0"
    repository: "file://charts/logstash"
  - name: kibana
    version: "0.1.0"
    repository: "file://charts/kibana"
