apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:26.0
          args: ["start-dev", "--import-realm"]
          ports:
            - containerPort: 8180
          env:
            - name: KC_HTTP_PORT
              value: "8180"
            - name: KEYCLOAK_ADMIN
              value: admin
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-keycloak-secret
                  key: admin-password
            - name: KEYCLOAK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-keycloak-secret
                  key: front-app-secret
            - name: ACCOUNTS_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-keycloak-secret
                  key: accounts-service-secret
            - name: CASH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-keycloak-secret
                  key: cash-service-secret
            - name: TRANSFER_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-keycloak-secret
                  key: transfer-service-secret
            - name: KEYCLOAK_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-keycloak-secret
                  key: user-password
          volumeMounts:
            - name: realm-config
              mountPath: /opt/keycloak/data/import
          readinessProbe:
            httpGet:
              path: /health
              port: 8180
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8180
            initialDelaySeconds: 60
            periodSeconds: 30
      volumes:
        - name: realm-config
          configMap:
            name: {{ .Release.Name }}-keycloak-realm
