apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-keycloak-secret
type: Opaque
stringData:
  admin-password: {{ .Values.adminPassword | quote }}
  front-app-secret: {{ .Values.global.secrets.frontAppClientSecret | quote }}
  accounts-service-secret: {{ .Values.global.secrets.accountsClientSecret | quote }}
  cash-service-secret: {{ .Values.global.secrets.cashClientSecret | quote }}
  transfer-service-secret: {{ .Values.global.secrets.transferClientSecret | quote }}
  user-password: {{ .Values.userPassword | quote }}
