apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-cash-service-config
data:
  SPRING_PROFILES_ACTIVE: kubernetes
  SPRING_APPLICATION_NAME: cash-service
  SERVER_PORT: "8082"
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: "http://{{ .Release.Name }}-keycloak:{{ .Values.global.keycloak.port }}/realms/{{ .Values.global.keycloak.realm }}"
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_ACCOUNTS_CLIENT_ID: cash-service
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_ACCOUNTS_AUTHORIZATION_GRANT_TYPE: client_credentials
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_ACCOUNTS_SCOPE: accounts
  SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_ACCOUNTS_ISSUER_URI: "http://{{ .Release.Name }}-keycloak:{{ .Values.global.keycloak.port }}/realms/{{ .Values.global.keycloak.realm }}"
  ACCOUNTS_SERVICE_URL: "http://{{ .Release.Name }}-accounts-service:8081"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "{{ .Release.Name }}-kafka:9092"
  SPRING_KAFKA_PRODUCER_KEY_SERIALIZER: org.apache.kafka.common.serialization.StringSerializer
  SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER: org.springframework.kafka.support.serializer.JsonSerializer
