apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-cash-service-secret
type: Opaque
stringData:
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_ACCOUNTS_CLIENT_SECRET: {{ .Values.global.secrets.cashClientSecret | quote }}
