apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-accounts-db
  labels:
    app: accounts-db
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: accounts-db
